### ISSUE TITLE
How to upload pictures

### ISSUE THREAD

**Issue by LilyGO** [moononournation/ESP32_Photo_Album#1]
Hi, Node js has just built a success (just understand the environment), make menuconfig has been set up WIFI, IP, port number. But then I encountered difficulties in uploading pictures. First of all, I need to use what tools to write it, because I am good at C language, Python, Arduino, but understanding of JavaScript just stay in the example of "hello, world". I hope you can give me some guidance or related sites. Of course, I will find answers on github and YouTube myself. But some pictures format and size (only JPG is it?) I still hope to get the original author's answer. Finally, I want to say. This is a surprising and happy process. Thank you.

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/35389310-2bd915ec-0212-11e8-9af3-f6d193e61790.png)

**Comment by moononournation** [comment]
Hi LilyGO, if you don't want to write code yet, please try my sample first: https://github.com/moononournation/nodejs-sharp-http-server
You may find more details at my instructables:
https://www.instructables.com/id/Kids-Photo-Album-With-Flashcard-Commercial/
My sample using Node.js sharp to read the photo files at photo sub folder, the library support JPEG, PNG and WebP images.
